version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/graphql-codegen-factories"
    schedule:
      interval: "daily"
    # We are only interested in security updates,
    # the following disables version updates:
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "production"
