name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn format
      - run: yarn lint
      - run: yarn build
        working-directory: packages/graphql-codegen-factories
      - run: yarn workspaces run test
